### ISSUE TITLE
Notifications 0.5.2

### ISSUE THREAD

**Issue by phil-davis** [owncloud/notifications#321] opened 2020-06-22 13:50 UTC
### Reason

- Release needed for #320 

### Translations

- Need to make sure that the translations of `Hello,` in necessary languages have come across from Transifex before branching for release.

### Product approval

- [x] Ping pmaier to check `info.xml` description and screenshot
- [x] Get approval on translations from pmaier

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [x] Create release branch with the format "release-$version"

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [x] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Test Changelog item + sanity tested with oC 10.5 with PHP 7.4

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by HanaGemela** [comment] 2020-06-29 12:44
@davitol RC1 https://github.com/owncloud/notifications/releases/tag/v0.5.1RC1

**Comment by davitol** [comment] 2020-07-09 07:49
Issue not fixed https://github.com/owncloud/enterprise/issues/4067#issuecomment-655963929 even when PR https://github.com/owncloud/notifications/pull/320 was included

**Comment by karakayasemi** [comment] 2020-07-14 18:54
The issue is fixed with https://github.com/owncloud/notifications/pull/322 . Do we need backport for it? I guess, better to create a new release branch from the current master.

**Comment by HanaGemela** [comment] 2020-07-15 07:52
@karakayasemi OK, I'll merge the current release branch back to master and we'll start over

**Comment by HanaGemela** [comment] 2020-07-15 12:34
@davitol ready for testing https://github.com/owncloud/notifications/releases/tag/v0.5.2RC1

**Comment by HanaGemela** [comment] 2020-07-15 12:43
Original issue is a P3 https://github.com/owncloud/enterprise/issues/4067 so setting the priority to P3 cc @pmaier1 @ChrisEdS

**Comment by pmaier1** [comment] 2020-07-15 15:59
JFYI - this app can only be released together with the server as it's bundled. Do we really need QA if there's only one change, making a string translatable? Generally the priority is fine.

**Comment by davitol** [comment] 2020-07-16 05:49
> Do we really need QA if there's only one change, making a string translatable?

@pmaier1 1st attempt of fixing that went wrong, and that's why we had to create an RC2 with the new fix. (see comment https://github.com/owncloud/notifications/issues/321#issuecomment-655966247) Finally i see we have rebuilt as RC1 again. I will test it today and if it works, it will be included in 10.5. if it is fine for you.

**Comment by pmaier1** [comment] 2020-07-16 08:10
I see, thanks for that explanation. Fine, not a blocker, though.

**Comment by davitol** [comment] 2020-07-16 14:33
Now it works. @HanaGemela @jnweiger :shipit: 

<img width="464" alt="Screenshot 2020-07-16 at 16 29 00" src="https://user-images.githubusercontent.com/10596560/87683986-04e4c980-c782-11ea-961e-2b1a801772df.png">
<img width="487" alt="Screenshot 2020-07-16 at 16 29 40" src="https://user-images.githubusercontent.com/10596560/87683992-0615f680-c782-11ea-833c-7a29981527dc.png">

**Closed** 2020-12-07 11:57 UTC
Labels: QA-ready, orga, p3-medium
